name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  MIX_ENV: test

jobs:
  test:
    name: Static analysis and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: '25.1.1'
          elixir-version: '1.14.1'

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v3
        id: mix-deps-cache
        env:
          cache-name: cache-elixir-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-

      - name: Retrieve Cached Build
        id: mix-build-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Catch compilation warnings
        run: mix compile --warnings-as-errors

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --min-priority high

      - name: Restore PLT cache
        uses: actions/cache@v3
        id: plt-cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            priv/plts

      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt

      - name: Run dialyzer
        run: mix dialyzer --format github

      - name: Run tests
        run: mix test --warnings-as-errors